name: Test Schedule

on:
  schedule:
    - cron: '*/5 * * * *'  # каждые 5 минут
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check time
        run: echo "Тест запущен в $(date)"
